import sys.io.File;
import sys.FileSystem;

import compiler.Mod;
import compiler.Mod.ResourcePath;

class ModpackBuilder
{
	static private var mods:Array<Mod> = new Array<Mod>();
	
	static public function build()
	{
		// Retrieve all mods
		// Mods are directories with a main.lua file
		Main.info("Searching for mods ...");
		Main.info("");
		FileSystemExplorer.explore(Sys.getCwd(), process);
		
		for(m in mods)
			m.report();
		Main.info("");
		
		// Let all the errors happen before writing anything
		for(m in mods)
			m.compile();
		
		// Check for collisions in the resource files
		var resources = new Array<ResourcePath>();
		var resourceNames = new Array<String>();
		for(m in mods)
			resources = resources.concat(m.getResourceFilenames());
		resourceNames = resources.map(function (r:ResourcePath) { return r.path; });
		for(r in resourceNames)
			if(resourceNames.indexOf(r) != resourceNames.lastIndexOf(r))
				throw "Collision in resource files : several mods have " + r + " : " +
					resources.filter(function (p:ResourcePath) { return p.path == r; })
					.map(function (p:ResourcePath) { return p.modName;});
		
		FileSystem.createDirectory(Main.outDir);
		// Flush the content and resources directories
		FileSystemExplorer.deleteDirectory(Main.outDir + "/content");
		FileSystemExplorer.deleteDirectory(Main.outDir + "/resources");
		var f = File.write(Main.outDir + "/main.lua", false);
		f.writeString("-- This file was automatically generated by the Binding of Isaac Afterbirth+ Modpack Builder, by Matrefeytontias\n");
		f.writeString("-- Please report issues at https://github.com/matrefeytontias/BoIMB/issues\n\n");
		f.writeString("local " + Main.outName + ' = RegisterMod("' + Main.modName + '", 1)\n');
		for(m in mods)
			m.writeCompiledResult(Main.outDir, f);
		f.close();
	}
	
	static private function process(path:String) : Bool
	{
		var r = FileSystem.isDirectory(path) && FileSystem.readDirectory(path).indexOf("main.lua") > -1;
		// Don't select the mod if it has the same name as the output mod
		if(r && path != Main.outDir)
			mods.push(new Mod(path));
		return !r;
	}
}